openapi: 3.0.3
info:
  title: WF Browser API
  description: |-
    This API is abstraction of SAP Cloud Foundry Workflow management and SAP Build Process automation API. 
    It ensures that WF Browser can be data source agnostic application. <br><br>
    [SAP Build Process Automation documentation](https://help.sap.com/docs/PROCESS_AUTOMATION) <br>
    [SAP Workflow service Documentation](https://help.sap.com/viewer/p/WORKFLOW_SERVICE)
  contact:
    email: vladimir.balko@effiis.cz
  version: 0.0.2
externalDocs:
  description: SAP Workflow service Documentation
  url: https://help.sap.com/viewer/p/WORKFLOW_SERVICE
tags:
  - name: Workflow Definitions
    description: WF definitions IDs allowed to browse
  - name: Workflow Instances
    description: WF instances with details
  - name: User Task Instances
    description: Retrieve instances by query parameters    
  - name: UI Configuration
    description: Configuration data for UI (columns, names)
paths:
  /v1/workflow-definitions:
    get:
      tags:
        - Workflow Definitions
      summary: Get list of definitions with basic data
      description: Get list of definitions with basic data. 
      operationId: getListOfDefinitions
      parameters:
      - name: userid
        in: query
        description: The ID of user - mostly email. Used to apply content filters.
        required: true
        schema:
          maxLength: 256
          minLength: 3
          type: string   
      responses:
        '200':
          description: succesful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Definition'
  /v1/workflow-instances:
    get:
      tags:
        - Workflow Instances
      summary: Retrieve all instances by query parameters
      description: Retrieves workflow instances by parameters.
      parameters:
      - name: definitionId
        in: query
        description: Specify the ID of the workflow definition. The ID is at most
          64 characters long.
        schema:
          maxLength: 64
          minLength: 1
          type: string    
      - name: userid
        in: query
        description: The ID of user - mostly email. Used to apply content filters.
        required: true
        schema:
          maxLength: 256
          minLength: 3
          type: string            
      responses:
        '200':
          description: Returns a list of workflow instances.
          content:
            application/json:
              schema:
                minItems: 0
                type: array
                items:
                  $ref: '#/components/schemas/WFInstance'
  /v1/workflow-instances/{workflowInstanceId}:
    get:
      tags:
        - Workflow Instances
      summary: Retrieve workflow instance by ID
      description: Retrieves the workflow instance with the specified workflow instance ID.
      parameters:
      - name: workflowInstanceId
        in: path
        description: The ID of the workflow instance, which should be retrieved. The workflow instance ID is 36 characters long.
        required: true
        schema:
          maxLength: 36
          minLength: 36
          type: string   
      - name: userid
        in: query
        description: The ID of user - mostly email. Used to apply content filters.
        required: true
        schema:
          maxLength: 256
          minLength: 3
          type: string            
      responses:
        '200':
          description: The requested workflow instance.
          content:
            application/json:
              schema:
                minItems: 0
                type: array
                items:
                  $ref: '#/components/schemas/WFInstance'
  /v1/workflow-instances/{workflowInstanceId}/tasks:
    get:
      tags:
        - Workflow Instances
      summary: List of task for this workflow instance
      description: Retrieves list of tasks for specified workflowid.
      parameters:
      - name: workflowInstanceId
        in: path
        description: The ID of the workflow instance, which should be retrieved. The workflow instance ID is 36 characters long.
        required: true
        schema:
          maxLength: 36
          minLength: 36
          type: string   
      - name: userid
        in: query
        description: The ID of user - mostly email. Used to apply content filters.
        required: true
        schema:
          maxLength: 256
          minLength: 3
          type: string            
      responses:
        '200':
          description: The requested workflow instance + tasks.
          content:
            application/json:
              schema:
                minItems: 0
                type: array
                items:
                  $ref: '#/components/schemas/TaskInstance'                  
  /v1/task-instances:
    get:
      tags:
        - User Task Instances
      parameters:
        - name: workflowInstanceId
          in: query
          description: The workflow instance ID for which the user task instances are returned. The workflow instance ID is 36 characters long.
          required: false
          explode: true
          schema:
            maxLength: 36
            minLength: 36
            type: string
        - name: userid
          in: query
          description: The ID of user - mostly email. Used to apply content filters.
          required: true
          schema:
            maxLength: 256
            minLength: 3
            type: string              
      responses:
        '200':
          description: succesful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TaskInstance'
  /v1/task-instances/{taskInstanceId}:   
    get:
      tags:
      - User Task Instances
      summary: Retrieve task by ID
      description: Retrieves the user task instance with the specified task instance ID.
      parameters:
      - name: taskInstanceId
        in: path
        description: The ID of the user task instance which should be retrieved. The ID is 36 characters long.
        required: true
        schema:
          maxLength: 36
          minLength: 36
          type: string    
      - name: userid
        in: query
        description: The ID of user - mostly email. Used to apply content filters.
        required: true
        schema:
          maxLength: 256
          minLength: 3
          type: string            
      responses:
        200:
          description: Returns the requested user task.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskInstance'
  /v1/task-instances/{taskInstanceId}/context:
    get:
      tags:
      - User Task Instances
      summary: Retrieve task context by ID
      description: Retrieves the context of a user task.
      parameters:
      - name: taskInstanceId
        in: path
        description: The ID of the user task for which the context should be retrieved.
          The ID is 36 characters long.
        required: true
        schema:
          maxLength: 36
          minLength: 36
          type: string
      - name: userid
        in: query
        description: The ID of user - mostly email. Used to apply content filters.
        required: true
        schema:
          maxLength: 256
          minLength: 3
          type: string            
      responses:
        200:
          description: Returns the context of the specified user task.
          content:
            application/json:
              schema:
                type: object
                description: The context of the user task.
              example:
                firstname: John
                lastname: Doe                          
  /v1/ui-config:
    get:
      tags:
        - UI Configuration
      summary: Get UI configuration data
      responses:
        '200':
          description: succesful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UIConfig'
    post:
      tags:
      - UI Configuration
      summary: Store UI configuration data
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UIConfig'
      responses:
        201:
          description: Returns the newly created workflow instance.
          content: {}
components:
  schemas:
    Definition:
      type: object
      properties:
        id:
          type: string
          maxLength: 64
        name:
          type: string
          maxLength: 255
        title:
          type: string
        attributes:
          type: array
          items:
            type: string
        
    TaskInstance:
      type: object
      properties:
        activityId:
          type: string
          maxLength: 255
          description: The definition ID of the user task instance. The ID is at most 255 characters long.
          example: 'usertask1'
        claimedAt:
          type: string
          format: date-time
          description: The time when the user task instance was claimed and its status changed to RESERVED.
        completedAt:
          type: string
          format: date-time
          description: The time when the user task instance status changed to COMPLETED.
        createdAt:
          type: string
          format: date-time
          description: The time when the user task instance was created.
        createdBy:
          type: string
          maxLength: 255
          description: The user who created the user task instance. The user ID is at most 255 characters long.
        description:
          type: string
          description: The description of the user task instance.
        id:
          type: string
          minLength: 36
          maxLength: 255
          description: The ID of the user task instance. The ID is at least 36 characters long.
        processor: 
          type: string
          maxLength: 255
          description: The user who is processing (has claimed) the user task instance. The user ID is at most 255 characters long.
          nullable: true
        recipientUsers:
          type: array
          items:
            type: string
          description: The recipient users of the user task instance.
          example: 
            - jan.test@zentiva.com
            - marian.komzik@kopa.com
        recipientGroups:
          type: array
          items:
            type: string
          description: The recipient groups of the user task instance.                     
        status:
          type: string
          description: The status of the user task instance.
          enum:
            - READY
            - RESERVED
            - CANCELED
            - COMPLETED 
        subject:
          type: string
          maxLength: 255
          description: The subject of the user task instance. The subject is at most 255 characters long.
        workflowDefinitionId:
          type: string
          maxLength: 64
          description: The definition ID of the workflow the user task instance belongs to. The ID is at most 64 characters long.
        workflowInstanceId:
          type: string
          minLength: 36
          maxLength: 255
          description: The instance ID of the workflow the user task instance belongs to. The ID is at least 36 characters long.
        priority:
          type: string
          enum:
            - LOW
            - MEDIUM
            - HIGH
            - VERY HIGH
        dueDate:
          type: string
          format: date-time
          description: The time when the user task instance is or was due to be COMPLETED.
        definitionId:
          type: string
          example: usertask1@cz.effiis.capexrdapprove
        lastChangeAt:
          type: string
          format: date-time
          description: The last time the user task instance was changed.
        applicationScope:
          type: string
          description: The scope to which the definition belongs. Either "own", "shared" or a named scope.
        rootInstanceId:
          type: string
          minLength: 36
          maxLength: 255
          description: The instance ID of the workflow the user task instance belongs to. The ID is at least 36 character long.
        taskComponent:
          type: string
          example: sapui5://capexrd.effiiscapexrdapprover-1.0.0/effiis.capex-rd-approver
          description: UI component used to show tasks data
        taskDecision:
          type: string
          example: approved
          description: Decision which took approver on this task (approved, rejected, submitted etc.)
    WFInstance:
      type: object
      properties:
        id:
          type: string
          minLength: 36
          maxLength: 255
          description: The workflow instance ID. The ID is at least 36 characters long.
        rootInstanceId:
          type: string
          minLength: 36
          maxLength: 255
          description: The instance ID of the workflow the user task instance belongs to. The ID is at least 36 character long.
        definitionsId:
          type: string
          maxLength: 64
          description: The ID of the workflow definition for which the instance was started. The ID is at most 64 characters long.
        definitionVersion:
          type: string
          description: The version of the workflow definition for which the instance was started.
        startedAt:
          type: string
          format: date-time
          description: The time when the workflow instance started.
        startedBy:
          type: string
          maxLength: 255
          description: The user who started the workflow instance. The user ID is at most 255 characters long.
        completedAt:
          type: string
          format: date-time
          nullable: true
          description: The time when the workflow instance status changed to COMPLETED.
        status:
          type: string
          enum: 
            - RUNNING
            - ERRONEOUS
            - SUSPENDED 
            - CANCELED
            - COMPLETED
        businessKey:
          type: string
          maxLength: 255
          description: The business key of the workflow instance. The business key of a workflow instance is limited to 255 characters.
        subject:
          type: string
          maxLength: 255
          description: The subject of the workflow instance. The subject of a workflow instance is limited to 255 characters.   
        attributes:
          type: array
          items:
            $ref: '#/components/schemas/Attributes'
    Attributes:
      type: object
      properties:
        name:
          type: string
          description: Technical name of the attribute
          example: 'Attr1'
        title:
          type: string
          description: Title of this attribute - usually show as column title
          example: Amount
        value:
          type: string
          description: Value of that specific attribute
          example: 138.22
    DynamicAttributes:
      type: object
      properties:
        path:
          type: string
          description: Path in the wf context, where the value is taken
          example: '$.context.data.input.OpexTotalEur'
        title:
          type: string
          description: Title of this attribute - usually show as column title
        attrName:
          type: string
          description: Technical name of the attribute
          example: 'Attr1'
        settings:
          $ref: '#/components/schemas/DynamicAttributesSettings'
    DynamicAttributesSettings:
      type: object
      properties:
        type:
          type: string
          enum: 
            - Date
            - DateTime
            - Amount
            - Address
            - Number
            - Boolean
        decimals:
          type: integer
          description: only for NUMBER and AMOUNT
          example: 2
        decimalSeparator:
          type: string
          example: ','
        currencyPath:
          type: string
          description: path in context to currency
          default: ''
          example: '$.context.data.input.Curr'
        houseNumPath:
          type: string
          example: '$.context.data.input.houseNumber'
        streetPath:
          type: string
          example: '$.context.data.input.contactStreet'
        cityPath:
          type: string
          example: '$.context.data.input.cityName'
        countryPath:
          type: string
          example: '$.context.data.input.countryFullName'
        zipCodePath:
          type: string
          example: '$.context.data.input.zipCode'
        display:
          type: string
          example: '{street} {houseNum}, {city}, {zipCode} {country}'     
    UIConfig:
      type: object
      properties:
        wfDefinitionId:
          type: string
          example: 'CapexRD'
        columns:
          type: array
          items:
            type: object
            properties:
              index:
                type: integer
                example: 1
                description: 'Order of column (1st, 2nd...)'
              title:
                type: string
              attribute:
                type: string
                example: 'Attr3'
              settings:
                $ref: '#/components/schemas/DynamicAttributesSettings'
